version: '3.1'

services:
  springboot:
    image: dockerhandson/spring-boot-mongo:1
    ports:
      - 8080:8080
    networks:
    - springappnetwork

  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db
    container_name: mongo
    networks:
    - springappnetwork

volumes:
  mongodb:

networks:
  springappnetwork:
